namespace StoryGenerator.Enums
{
    public enum Motivation
    {
        Jealousy,
        Greed,
        Lust,
        Revenge,
        Fear,
        Money,
        Honor,
        Duty,
        Dept,
        GreaterGood,
        Science,
        Expectations,
        ReligiousFanatism,
        SelfDiscovery,
        Guilt,
        AWishToPutOthersInBadPosition,
        AWishToProtectLovedOnes,
        AWishToBreakFree,
        AWishToGainAffection,
        AWishToGainPower,
        AWishToComeHome,
        AWishToGainApproval,
        AWishToProveWorth,
        AWishToShowof,
    }
}
